### ISSUE TITLE
MathJax JS 引入错误

### ISSUE THREAD

**Issue by shajiquan** [shajiquan/gitit-package#1]
如有请留言，一起交流。不过我写不了 `Haskell` 啊！！！

**Comment by Edenharder** [comment]
你好，我使用你的模板发现数学公式不能正常显示，可能和page.st有关系。怎么才能支持数学公式呢？谢谢你！
我直接安装Bootstrap 模板错误提示：

```
./build.sh: line 19: ~/Wiki/node_modules/minify/bin/minify: No such file or directory
```

这该怎么办呢？

替换掉你的mathjax源问题解决了。

**Comment by shajiquan** [comment]
@Edenharder Hi，因为数学公式我基本不用，所以这块当时测试的并不多，只是引入了 bootcss cdn 上的一个源，然后把 gitit demo 里的测试通过就完事了。

gitit 默认使用的是一个国外网站的 JS文件，但在国内似乎连接有问题，于是当时我就换成了国内的镜像。

这两天会更新，允许用户通过自定义配置来决定：
- 是否启用数学公式
- 引用哪个源
- 在哪些页面排除引入（在某些页面其实完全不需要引入 mathjax 源，比如登录、分类）

**Comment by shajiquan** [comment]
@Edenharder 您现在使用正常的是哪个源？另外您现在使用的 gitit 的版本是多少？浏览器是怎样的？

**Comment by Edenharder** [comment]
源我是引用的

```
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"
></script>
```

gitit本身应该就是用的这个。我用的gitit 0.12.0.1，浏览器是Chrome。
我对这些东西都不太懂，希望能和你多交流学习。

**Comment by Edenharder** [comment]
你好，怎么用本地的编辑器修改或新建文件呢？

**Comment by shajiquan** [comment]
@Edenharder 我把这个源回头改一下吧，实在不成就改成官方默认的。或者您发几个数学公式，我开发阶段测试一下。

本地编辑器的话，得配合 git 命令来操作。我文档里有写，不过文档太长了，你可能没看到。

### 通过 shell 来编辑 wiki

`wikidata` 是一个仓库目录，只要该文件夹下的文件被 `git add` 到仓库并执行了 `git commit`，gitit 将会把它们当作 wiki 条目加入到系统中。

因此，我们可以通过 shell 下的一系列操作来编辑 wiki。比如：

<pre>
cd /path/to/your/wikidata
touch new_page.md
echo "hello shajiquan" >> new_page.md
git add new_pge.md
git commit -m "add new_page.md file"
echo "new line" >> old_page.md
git add old_page.md
git commit -m "update old_page.md "
git push origin master
</pre>

**Comment by shajiquan** [comment]
@Edenharder

如果用本地编辑器的话，只需要在编辑器里新建文件 `abc.md`，编辑完再 git commit。如果编辑器带了 git 相关插件，可能会更方便一些。

**Comment by Edenharder** [comment]
前面的都没问题，但当我

```
$ git push origin master

fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by shajiquan** [comment]
@Edenharder 这个是因为您尝试将您本地的仓库更新 push 到我的仓库来，所以报错了。

如果您只在本地搭建一个 gitit 的话，那么不需要 push，您的本地运行一个 gitit server 就好了。

如果您要把您的 wikidata 也就是那些 wiki 页面 push 到自己仓库里，那么需要保证 ~/gitit/wikidata 是您自己的仓库。

在终端里，在 `~/gitit` 和 `~/gitit/wikidata` 两个目录下运行 `git remote -v` 的结果必须不一样。

也就说 `~/gitit` 其实是你 clone 的我的代码（仓库），但 `~/gitit/wikidata` 则应该是您自己的仓库。

``` bash
# gitit 文件夹，也是 gitit-bigger 文件夹
~/gitit 

# wikidata 文件夹，这是真正放置 wiki 页面的地方
# 这个文件夹，必须是您自己的一个仓库，您在这个仓库里 add、commit、push
~/gitit/wikidata
```

另外，我已经更新了代码，MathJax 的问题应该已经修复了。另外可以自定义 mathjax.js 文件的地址，不过我现在还没有更新文档，只在 commit message 里写了一下。

这两天我会更新一下文档，重新组织一下，更方便用户上手和修改。

如果要更前 gitit-bigger 代码，在 gitit-bigger 路径下运行 `git pull origin master` 然后重启 gitit 服务即可。

**Comment by Edenharder** [comment]
嗯，但即使只搭建本地的gitit，用本地的编辑器编辑之后也是需要执行`git add, git commit`才能生效，是这样吧？

**Comment by shajiquan** [comment]
@Edenharder 是的，必须 git add、git commit。

**Comment by shajiquan** [comment]
@Edenharder 已更新。
- 增加了一些配置项
- 修复了 MathJax JS 引入问题；

有问题请新开 issue 我再来处理。

现在这个 issue 就先关了。

谢谢。
