### ISSUE TITLE
More English?

### ISSUE THREAD

**Issue by steckerhalter** [shajiquan/gitit-package#11]
Hi, really nice theme and extensions for Gitit (especially the ACE editor)

It would probably help to make more of the documentation available also in English so more people can use and know about it. What do you think?

**Comment by shajiquan** [comment]
@steckerhalter Sure, thank you!!! 

My English is very poor, so I haven't write docs in English. 

I've add an docs/en folder, feel free to add English docs there. 

I will update the README.md file when I receive your pull request, and add more English introduction and add links to docs/en.

Thank you!

**Comment by shajiquan** [comment]
BTW, don't foeget to rebase the upstream.

**Comment by steckerhalter** [comment]
Allright, I'll see what I can do...
