### ISSUE TITLE
新建页面的没有头部定义信息，Categories 页面未能列出所有的页面

### ISSUE THREAD

**Issue by choicky** [shajiquan/gitit-package#16]
今天新建了个 Gitit Bigger ，在 [http://us4.fei-xing.com:7500](http://us4.fei-xing.com:7500) 。总体上还挺满意的，多谢。

翻了说明，没找到答案，所以在这里提问两个问题。

## 新建页面时，页面头部是空的，没有类似于下面的声明：

```
---
format: Markdown
categories: Markdown
---
```
如需要用户每新建一个页面都输入，太重复劳动了。

## 顶部的`Categories`不能把同一个 category 的所有页面列出来

我把几个页面都加了 `categories: Markdown` ，`Categories`页面最初是空的，大概十分钟后才显示出`Markdown`。 但是，点击这个 `Markdown` 却只显示一个页面，而不是把所有的页面都显示出来。

**Comment by menduo** [comment]
Sorry，才注意到这个 issue。

你需要用这样的语法：

```
---
title: 什么什么
categories: markdown, abc
...
```

之所以是这样，因为 gitit 早期的版本只支持这个语法。最新版支持 `---`。



第二个问题，用上面这种语法后，就可以解决。
