### ISSUE TITLE
ace 编辑器中无法正常输入中文

### ISSUE THREAD

**Issue by jzoe** [shajiquan/gitit-package#17]
嗨，您好！非常感谢您的开源贡献！我正在部署你的 gitit-bigger 系统，但是在部署完后，发现编辑页面中无法正常输入中文，比如我用搜狗拼音输入"ninhao"，回车后变成了 “ninhao 您好”，而不是 "您好"。

请问您有遇到这个问题吗？

**Comment by jzoe** [comment]
#ces测试 双击shuangji双击双击erq而且hui而且会chongf

**Comment by jzoe** [comment]
#ces测试 双击shuangji双击双击erq而且hui而且会chongf

这是我在输入： “测试，双击而且会自动复制 “ 时的结果。

**Comment by choicky** [comment]
@jzoe 在 chrome 下，用QQ输入法输入也能重现这个问题。

其他浏览器，例如IE Firefox Edge 都不会出现这个问题。

感觉chrome对中文用户的坑挺多的。例如，iOS 下，用搜狗输入法在 chrome 的地址栏输入英文，也会出现类似的现象。

我之前一直以为是搜狗输入法的bug，现在觉得，应该是 chrome 的bug

**Comment by jzoe** [comment]
我确实用的是chrome 浏览器，呜呜，这个坑有点大😂😂那看来只能禁用ace插件了
发自网易邮箱大师
在2017年01月10日 18:50，Choicky ZHOU 写道:@jzoe 在 chrome 下，用QQ输入法输入也能重现这个问题。
其他浏览器，例如IE Firefox Edge 都不会出现这个问题。
感觉chrome对中文用户的坑挺多的。例如，iOS 下，用搜狗输入法在 chrome 的地址栏输入英文，也会出现类似的现象。
我之前一直以为是搜狗输入法的bug，现在觉得，应该是 chrome 的bug

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/menduo/gitit-bigger","title":"menduo/gitit-bigger","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/menduo/gitit-bigger"}},"updates":{"snippets":[{"icon":"PERSON","message":"@choicky in #17: @jzoe 在 chrome 下，用QQ输入法输入也能重现这个问题。\r\n\r\n其他浏览器，例如IE Firefox Edge 都不会出现这个问题。\r\n\r\n感觉chrome对中文用户的坑挺多的。例如，iOS 下，用搜狗输入法在 chrome 的地址栏输入英文，也会出现类似的现象。\r\n\r\n我之前一直以为是搜狗输入法的bug，现在觉得，应该是 chrome 的bug"}],"action":{"name":"View Issue","url":"https://github.com/menduo/gitit-bigger/issues/17#issuecomment-271544879"}}}

**Comment by jzoe** [comment]
@choicky 我觉得应该是 gitit-bigger 包装 ace 的时候留下的 bug，正在找，如果有解决方案了，我会在这个 issue 中贴出来。

**Comment by choicky** [comment]
@jzoe ace 那边也有人提这个问题，例如 https://github.com/ajaxorg/ace/issues/3099 。也有人说最新版的 ace 解决了这个问题。但是，我用最新的ace的js替换 gitit bigger 的，问题依旧。

你找到解决方案了通知一下。

另外，你的wiki在哪？我去参观下

**Comment by jzoe** [comment]
我早上也感觉是这个问题，然后用最新的 ace 替换后 ，问题解决了。

Sorry，我这 wiki 是内部使用，不对外开放。

**Comment by choicky** [comment]
@jzoe 难道是我替换的方式不对？能提供一下替换方法吗？

**Comment by choicky** [comment]
@jzoe 我忘了刷新浏览器缓存。。。 刷新后正常了。
