### ISSUE TITLE
错误地自动将半角引号转成全角

### ISSUE THREAD

**Issue by die4live** [shajiquan/gitit-package#5]
用 docker 试一下, 发现一个引号自动转换的问题: 编辑时写的是 `'`, 但是页面中显示的却是 `’`, 双引号也有这个问题, 看了下你的示例 [危机百科 - 首页](http://wiki.shajiquan.com/) 也是这样, 官方网站也是如此

不知道是什么原因造成的?

**Comment by shajiquan** [comment]
我测试了一下，是 Gitit 自己的 Bug，即使是在最新的 0.12.x 上也有。

我已经向官方汇报这个问题，希望早日解决。

sorry，这是个比较严重的问题呢。我先前还没注意到过呢。似乎在代码段里的是没问题的。

**Comment by shajiquan** [comment]
@die4live 问了 Gitit 官方，答复是，他们对此的方案是「智能引号」（什么鬼！），并且不支持自定义。

作者说，如果要使用非全角引号的话，可以使用反斜杠，但不建议这么做。

这个只能等官方给更好的解决方案了。

其实我觉得，默认应该是普通的，如果用户真要用全角了，他会自己去处理嘛。

**Comment by die4live** [comment]
@shajiquan 哈哈, 我也去围观了下, 这作者估计是太懒了..

**Comment by shajiquan** [comment]
@die4live  看到你的啦哈哈，你的英文很好啊，能写能读。我基本只能读。

作者有回复说会处理，但似乎精力有限，希望有人能修复然后提交 pr。但我搞不来 haskell，源码看着头晕。

谢谢你的围观！

**Comment by die4live** [comment]
@shajiquan 是啊, 看到 Haskell 我就怂了:)
