### ISSUE TITLE
Categories 页面显示不正常

### ISSUE THREAD

**Issue by ghost** [shajiquan/gitit-package#6]
你的分类界面
![](http://7ktvu8.com1.z0.glb.clouddn.com/qqb.png)
我这边
![](http://7ktvu8.com1.z0.glb.clouddn.com/qqa.jpg)

多了一个Categories的一栏，请问你那边是改了什么配置吗？

**Comment by shajiquan** [comment]
没错的。

你用的应该是较新版的 gitit，而我的那个是一个比较旧的版本。

新版本会在每个 category 页面的下方，多出一些 categories 来，这是因为这个 category 曾经和其他的 category 被组合使用过。

当你在 category/`a` 页面时，可能下面的 categories 会显示 `+b`，当你点击 `+b` 的链接时，展示的结果是那些同时使用了这两个分类的页面。(此时当前页面的网址变成了 `/_category/a,b`)

而你在 `category/a,b` 时，就会出现 `-b` 一类的字样。

新版本的 gitit，即使你浏览的是一个分类页面（/_category/a）而非 (/_category/a,b,c) 时，也一样会出现那个 `-`，其实就是 `-` 去本 category，返回到 `categories` 页面。

**Comment by ghost** [comment]
@shajiquan 刚试了下,的确是组合使用来的.
之前不知道这作用,一直觉得多了这个看起来好别扭,
谢谢了.

**Comment by shajiquan** [comment]
@wbing-xu 不客气
