### ISSUE TITLE
修改配置文件编辑器无法显示

### ISSUE THREAD

**Issue by hlyang1992** [shajiquan/gitit-package#9]
将配置_base_config.js_文件`"setTheme": "ace/theme/github"` 修改为`"setTheme": "ace/theme/monokai"`后，编辑的时候编辑器无法显示，用浏览器查看源码，发现_base_config.js_最后会有乱码字符产生，一个黑色的平行四边形中间带一个问号。文件是用_utf8_编码保存的，只要修改配置文件都会出现这种情况。

**Comment by shajiquan** [comment]
您的 wiki 是公开可访问的吗？我看一下。我这边还没有发现这个问题。

**Comment by hlyang1992** [comment]
刚刚我有重新配置了下， 发现以前的问题没有了，具体什么问题也没找出来。非常感谢，这个非常好用。
